---

- hosts: all
  become: no
  tasks:
    - name: Include timezone
      ansible.builtin.include: timezone.yml

    - name: Include minimal-vimrc
      ansible.builtin.include: minimal-vimrc.yml

    - name: Include apache and redis
      ansible.builtin.include: apache-redis.yml

    - name: fzf
      ansible.builtin.include: fzf.yml

    - name: git-prompt
      ansible.builtin.include: git-prompt.yml

    # - name: Testing fact
    #   become: no
    #   become_user: vagrant
    #   shell: echo {{ ansible_facts['hostname'] }}
    #   register: out

    # - debug: 
    #       var: out.stdout_lines

    # - debug: 
    #       var: ansible_user_dir

